# Table of Contents

This diary explores my thoughts about each method we cover in class. This is my 3rd class dedicated to remote sensing with the previous 2 being from undergrad. Specifically, I have experience (from the first class) using ENVI to perform many remote sensing tasks such as classification and LiDAR point cloud analysis, and from the second class I have used Python as a tool mostly for classification and difference index analysis.

Additionally, I was part of a team from January-June 2025 that was using LiDAR data (DEM) to assess solar energy potential of rooftops in Northern Virginia, USA. I draw on these experiences in this diary as a source of questions and background for both the methods covered and literature analysis.

Week 1:

-   [Introduction to Remote Sensing](https://ohughes-2.github.io/Quarto_Diary/Week1.html)

Week 2:

-   [Quarto Books and Xaringan Presentations](https://ohughes-2.github.io/Quarto_Diary/Week2.html)

Week 3:

-   [Corrections and Enhancements](https://ohughes-2.github.io/Quarto_Diary/Week3.html)

Week 4:

-   [Project Case Study: Solar Energy in Loudoun County, Virginia](https://ohughes-2.github.io/Quarto_Diary/Week4.html)

Week 6:

-   [Introduction to Google Earth Engine](https://ohughes-2.github.io/Quarto_Diary/Week5.html)

Week 7:

-   [Remote Sensing and Machine Learning](https://ohughes-2.github.io/Quarto_Diary/Week6.html)

Week 8:

-   [Sub-Pixel and OBIA Classification](https://ohughes-2.github.io/Quarto_Diary/Week7.html)

Week 9:

-   [SAR Damage Detection](https://ohughes-2.github.io/Quarto_Diary/Week8.html)
